using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using DataForSeo.Client.Models;

namespace DataForSeo.Client.Models
{

    public class MessageAiOptimizationLlmResponseElementItem  : BaseAiOptimizationLlmResponseElementItem 
    {

        /// <summary>
        /// reasoning chain sections
        /// <br/>array of objects containing the reasoning chain sections generated by the LLM
        /// </summary>
        [JsonProperty("sections", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<LlmMessageSectionInfo> Sections { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }
    }
}